#!/usr/bin/env bash
echo "Installing env"
mkvirtualenv -p ~/Downloads/pypy3-2.4.0-osx64/bin/pypy3 historia

echo "Installing pip dependencies"
pip install -r requirements-r.txt
pip install -r requirements.txt

echo "Installing project"
python setup.py install

echo "Setting up develop mode"
python setup.py develop
